<b> Get Geospatial Coordinates of canada from csv file </b>

In [1]:
import numpy as np
import pandas as pd

df_geocode = pd.read_csv('Geospatial_Coordinates.csv')
df_postcode = pd.read_csv('canada_postcode.csv')

In [2]:
df_postcode.shape

(103, 4)

Print the shape of newly created Dataframe

geo location and addresses are read from csv files into dataframe 
Addresses which were edited in previous notebook were stored by me to read in this notebook

Print the shape of geocode dataframe which contains geo location of all postcodes

In [3]:
df_geocode.shape

(103, 3)

In [4]:
df_postcode.head(10)

,Unnamed: 0,Postcode,Borough,Neighbourhood
0,1,M1B,Scarborough,"Rouge, Malvern"
1,2,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
2,3,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,4,M1G,Scarborough,Woburn
4,5,M1H,Scarborough,Cedarbrae
5,6,M1J,Scarborough,Scarborough Village
6,7,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park"
7,8,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge"
8,9,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West"
9,10,M1N,Scarborough,"Birch Cliff, Cliffside West"

In [7]:
df_geocode.head(10)

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476
5         M1J  43.744734 -79.239476
6         M1K  43.727929 -79.262029
7         M1L  43.711112 -79.284577
8         M1M  43.716316 -79.239476
9         M1N  43.692657 -79.264848

In [5]:
df_Spatial=df_postcode

Create a new dataframe with postcode,address and their corresponding geo location

In [6]:
df_Spatial['Latitue']=df_geocode['Latitude']
df_Spatial['Longitude']=df_geocode['Longitude']

In [7]:
df_Spatial.head(10)

,Unnamed: 0,Postcode,Borough,Neighbourhood,Latitue,Longitude
0,1,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,2,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,3,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,4,M1G,Scarborough,Woburn,43.770992,-79.216917
4,5,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,6,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,7,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,8,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,9,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,10,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848

In [8]:
df_Spatial.drop(df_Spatial.columns[0], axis=1, inplace=True)

Delete unnecessary column

Save the newly edited Post code and Addresses with geolocation in a csv file for further use

In [9]:
df_Spatial.to_csv('canada_postcodeWithGeo.csv')
df_Spatial.shape

(103, 5)

In [24]:
df_Spatial.head(20)

,Borough,Neighbourhood,Latitue,Longitude
0,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,Scarborough,Woburn,43.770992,-79.216917
4,Scarborough,Cedarbrae,43.773136,-79.239476
5,Scarborough,Scarborough Village,43.744734,-79.239476
6,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
12,Scarborough,Agincourt,43.794200,-79.262029
13,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",43.781638,-79.304302
14,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St...",43.815252,-79.284577
15,Scarborough,L'Amoreaux West,43.799525,-79.318389
16,Scarborough,Upper Rouge,43.836125,-79.205636
17,North York,Hillcrest Village,43.803762,-79.363452
18,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
19,North York,Bayview Village,43.786947,-79.385975

In [ ]:
Printing top ten rows of